version: "3.8"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - grafana-volume:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
  influxdb:
    image: quay.io/influxdb/influxdb:2.0.0-beta
    container_name: influxdb
    restart: always
    ports:
      - 9999:9999
    networks:
      - monitoring
    volumes:
      - influxdb-volume:/root/.influxdbv2
networks:
  monitoring:
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
