version: '3.8'
services:
  grafana:
    image: grafana/grafana:9.5.1
    container_name: grafana
    restart: always
    ports:
      - 3333:3000
    networks:
      monitoring:
        ipv4_address: 172.23.0.3
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - grafana-volume:/var/lib/grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
      GF_RENDERING_SERVER_URL: http://172.23.0.4:8081/render
      GF_RENDERING_CALLBACK_URL: http://172.23.0.3:3000/
      GF_LOG_FILTERS: rendering:debug

  influxdb:
    image: influxdb:2.7.0
    container_name: influxdb
    restart: always
    ports:
      - 9999:8086
    networks:
      monitoring:
        ipv4_address: 172.23.0.2
    volumes:
      - /data/docker_volumes/influxdb:/var/lib/influxdb2

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: grafana_renderer
    ports:
      - 8081
    networks:
      monitoring:
        ipv4_address: 172.23.0.4
    environment:
      ENABLE_METRICS: 'true'

networks:
  monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.1/16

volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
