version: '3.8'
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 80:3000
    networks:
      monitoring:
        ipv4_address: 172.23.0.3
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - grafana-volume:/var/lib/grafana
    environment:
      GF_PATHS_CONFIG: /etc/grafana/grafana.ini
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource

  influxdb:
    image: quay.io/influxdb/influxdb:v2.0.4
    container_name: influxdb
    restart: always
    ports:
      - 9999:8086
    networks:
      monitoring:
        ipv4_address: 172.23.0.2
    volumes:
      - influxdb-volume:/root/.influxdbv2
networks:
  monitoring:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet:  172.23.0.1/16
volumes:
  grafana-volume:
    external: true
  influxdb-volume:
    external: true
